version: "3.8"

services:
  frontend:
    build:
      dockerfile: Dockerfile.prod
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env.production
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules


