name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo su
            cd /var/www/
            sudo rm -rf job_search
            sudo git clone https://github.com/walia1454/job_search.git
            cd job_search
            FRONTEND_CONTAINER_ID=$(sudo docker ps -aqf "name=frontend")
            if [ ! -z "$FRONTEND_CONTAINER_ID" ]; then
              sudo docker container stop $FRONTEND_CONTAINER_ID
              sudo docker container rm $FRONTEND_CONTAINER_ID
            fi
            docker compose -f docker-compose.prod.yml up -d --build
